### PR TITLE
ENH: Deep revision of the workflow

### PR DESCRIPTION
**Pull request by oesteban**
- Remove the high-resolution path (use original images')
- Use RegridToZooms smoothing.

### CODE REVIEW

**Comment by oesteban** [comment]
@mgxd - can you test this revision on all the data before we merge?

**Comment by mgxd** [comment]
we'll wait til all finish, but so far things look good.

**Comment by oesteban** [comment]
One thing to have in mind is that niworkflows is pinned to a commit of my fork

**Comment by mgxd** [comment]
yep, that's accounted for

**Comment by mgxd** [comment]
@oesteban what's the status of this? can you rebase?

**Comment by mgxd** [comment]
closing as this has gone stale

**Pull request closed without merging**
