### PR TITLE
FIX: Gracefully handle longitudinal/long format participants TSV

### LINKED ISSUE #388: Issue finding age in months from participants.tsv for v24.0.0
### What happened?

When submitting recent processing jobs with v24.0.0 I have been running into an error when trying to collect the age in months information from the participants.tsv that I've been using. Specifying the age in months with the `--age-months` flag and not using a participants.tsv can get around in the error in the meantime. 

### What command did you use?

```shell
singularity run --cleanenv \
 -B ${data_dir}/bids_dir/sub-${subj_id}_ses-${ses_id}:/bids_dir \
 -B ${data_dir}/processed/nibabies/sub-${subj_id}_ses-${ses_id}:/output_dir \
 -B ${data_dir}/work_dir/nibabies/sub-${subj_id}_ses-${ses_id}:/wd \
 -B ${data_dir}/processed/bibsnet/sub-${subj_id}_ses-${ses_id}:/derivatives \
 -B ${run_dir}/license.txt:/license.txt \
 /home/faird/shared/code/external/pipelines/nibabies/nibabies_24.0.0.sif \
 /bids_dir /output_dir participant \
--output-spaces MNI152NLin6Asym:res-2 \
--fs-license-file /license.txt \
--omp-nthreads 8 \
--nprocs 8 \
--cifti-output 91k \
-vv \
--project-goodvoxels \
--fd-radius 45 \
--derivatives /derivatives \
--surface-recon-method ${recon} \
-w /wd


and here is the first 5 lines of the participants.tsv I was using:
participant_id	session	age
sub-100619	ses-17mo	17
sub-100619	ses-23mo	23
sub-102606	ses-10mo	10
sub-102606	ses-19mo	19
```

### What version of NiBabies are you using?

v24.0.0

### Relevant log output

```shell
Traceback (most recent call last):
  File "/opt/conda/envs/nibabies/bin/nibabies", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/conda/envs/nibabies/lib/python3.11/site-packages/nibabies/cli/run.py", line 62, in main
    retval = build_workflow(config_file)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/nibabies/lib/python3.11/site-packages/nibabies/cli/workflow.py", line 76, in build_workflow
    retval['workflow'] = init_nibabies_wf(config.execution.unique_labels)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/nibabies/lib/python3.11/site-packages/nibabies/workflows/base.py", line 124, in init_nibabies_wf
    age = parse_bids_for_age_months(config.execution.bids_dir, subject_id, session_id)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/nibabies/lib/python3.11/site-packages/nibabies/utils/bids.py", line 261, in parse_bids_for_age_months
    age = _get_age_from_tsv(participants_tsv, index_column='participant_id', index_val=subject)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/nibabies/lib/python3.11/site-packages/nibabies/utils/bids.py", line 284, in _get_age_from_tsv
    idx = df.index[df[index_column] == index_val].item()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/nibabies/lib/python3.11/site-packages/pandas/core/base.py", line 418, in item
    raise ValueError("can only convert an array of size 1 to a Python scalar")
ValueError: can only convert an array of size 1 to a Python scalar
```

### Add any additional information or context about the problem here.

If any more information is needed please let me know. Happy to help with testing/troubleshooting as well, thanks!

### PR DESCRIPTION
**Pull request by scott-huberty**
fixes #388

### CODE REVIEW

**Comment by scott-huberty** [comment]
> Seems like the problem is multiple results are returned when querying the participants.tsv, since we aren't dual indexing with <subject, session> ....  In short, you can either be explicit and denote age within the tsv as `age_months`, `age_years`, etc., or use `age` and include a sidecar file to the tsv describing the column's units.

Originally posted in https://github.com/nipreps/nibabies/issues/388#issuecomment-2334294892

@mgxd Indeed this is the problem but apparently it worked fine in 23.X (and is technically BIDS compliant, no?). So I would tend to think that it is a code regression from #376 , or do you consider it an API change (without a deprecation cycle), or a bug fix?

**Comment by mgxd** [comment]
so there are 2 issues to handle:

1) parsing `participants.tsv` for both participant / session fields

2) handling unit-less "age" values 

for (1) - yes we should have a way of handling it.

for (2) - it's an api change. previously we just used the value found and assumed it was in months..
https://github.com/nipreps/nibabies/blob/22c68278bd0054ab7a15de5e13e3d3f4da5d3b41/nibabies/utils/bids.py#L373

i'm inclined to keep this new behavior, as that assumption becomes less certain when processing 1 year olds+
looking at #388 i think we definitely need to do a better job communicating this to the user, either through a warning or maybe even an error.

**Comment by scott-huberty** [comment]
OK so if I'm understanding correctly then the path forward is:

- In this PR we continue the path of making sure Nibabies can once again parse `participants.tsv` files that are in long format (e.g. they have a `particpiant_id` column and a `session`/`age_[unit]` column or something like that). 

- In this PR or a follow up PR we can add some logic to throw an error/warning if the `participants.tsv` column contains an `age` column without a corresponding `participants.json` sidecar file that specifies the unit of the age column in the `participants.tsv` file (day, weeks, months years etc). I think I'd prefer to throw an error so that we explicitly enforce a standard.

How does that sound?

**Comment by mgxd** [comment]
> add some logic to throw an error/warning if the participants.tsv file contains an age column without a corresponding participants.json

this would apply to all relevant TSV files (scans.tsv, sessions.tsv, etc)

but sounds good, and thanks for taking this on 😄

**Comment by scott-huberty** [comment]
> and thanks for taking this on 😄

Don't thank me until it's actually done 😆 I'll try not to let it sit. And @lundq163 I'll leave you with some directions to checkout this branch and mount it to your container in case you don't want to wait around for me.

**Comment by scott-huberty** [comment]
@lundq163 In case you beat me to it (or for future reference). If you already know this you can ignore me!

Typically when debugging I will do something like.


1. Fork Nibabies and clone my fork to my computer.

2. Mount my local copy of Nibabies to the image by adding this to the Docker/Singularity command:



```bash
# Docker
-v /home/path/to/copy/of/nibabies/nibabies/:/opt/conda/envs/nibabies/lib/python3.11/site-packages/nibabies:ro /home/hubers2/dev/images/nibabies_image.sif

```

```bash
# Singularity
 -B /home/path/to/copy/of/nibabies/nibabies/:/opt/conda/envs/nibabies/lib/python3.11/site-packages/nibabies:ro /home/hubers2/dev/images/nibabies_image.sif
```

- Now, you can make changes to the files in your local copy of Nibabies, and they should take effect in the Nibabies run. 

And if I want to enter into the container with the codebase mounted, without actually running Nibabies, I'd do:

```bash
# Docker
docker run -it --entrypoint /bin/bash  -v /home/path/to/copy/of/nibabies/nibabies/:/opt/conda/envs/nibabies/lib/python3.11/site-packages/nibabies:ro nipreps/nibabies:latest
```

```
# Singularity
singularity shell --cleanenv -B /home/path/to/copy/of/nibabies/nibabies/:/opt/conda/envs/nibabies/lib/python3.11/site-packages/nibabies:ro /home/hubers2/dev/images/nibabies_image.sif
```


For example I did this while working on this PR, because I made changes to a test in `nibabies/utils/tests/test_bids`, and I wanted to test that it had the expected effect. So I entered the container, and ran the test with:

```bash
pytest /opt/conda/envs/nibabies/lib/python3.11/site-packages/nibabies/utils/tests/test_bids.py -k test_get_age_from_tsv
```

There's probably a lot more that can be said, but I'll just stop there!

**Comment by mgxd** [comment]
Hi @scott-huberty, looking back at this I don't think this use case is BIDS compliant.

From the `participants.tsv` [docs](https://bids-specification.readthedocs.io/en/stable/modality-agnostic-files.html#participants-file)
> Each participant MUST be described by one and only one row.

Which makes sense, as each TSV should have an index column. Finer age information should be propagated to either the `sessions.tsv` or `scans.tsv`.

**Comment by scott-huberty** [comment]
@mgxd ah yeah you are right. I'm surprised that `BIDS-Validator` doesn't validate against this. 

In that case maybe we can just add some code to `_get_age_from_tsv` to throw a more helpful error than the index error that was thrown before?

**Comment by mgxd** [comment]
Closing this after #395 - if you still run into problem, please open an issue

**Pull request closed without merging**
