### PR TITLE
FIX: Ensure version is written to version file

### PR DESCRIPTION
**Pull request by mgxd**
Hopefully addresses #142 ...

cc @effigies for another pair of eyes

### CODE REVIEW

**Comment by effigies** [comment]
Do you have a test where you run `docker run <image> --version`? If so, that will help...

**Comment by mgxd** [comment]
Actually, I think the problem is the `.dockerignore` is severely lacking - making `/src/nibabies` a git repository...

but more tests don't hurt

**Comment by mgxd** [comment]
merging and testing with a new rc

**Comment by effigies** [comment]
Did you test just building locally and checking the version?

**Comment by effigies** [comment]
And have you verified that versioneer has Oscar's VERSION hack in it?

**Comment by mgxd** [comment]
> And have you verified that versioneer has Oscar's VERSION hack in it?

This is what I was missing!

**Pull request merged**
