### PR TITLE
ENH: Revise T1w-to-T2w co-registration (and T1w brainmask)

### PR DESCRIPTION
**Pull request by oesteban**
This PR splits the T1w-to-T2w co-registration out from the brain extraction
workflow (for clarity and to ease debugging).

The registration parameters have been also revised and a nonlinear step
has been added to account for nonlinear differences between the two
images.

### CODE REVIEW

**Comment by oesteban** [comment]
@mgxd the adaptations to the other workflows (and removal of the t1 path from the brain extraction) should be coming in soon.

**Comment by oesteban** [comment]
I haven't tested this myself yet, but I think it is ready for you to give it a try.

The three modules I've edited really needed a cleanup, I have removed a few unused references and run black.

I would make counting on the T2w image the default behavior. There'll be time for sophistication, and also more possibilities when better templates are available for brain extraction.

I'm a little worried that ``ValidateImage`` pops here and there. Also, the massaging of inputs should happen before ``mri_robust_template``. I think those are improvements to consider in a near future but definitely outside this PR. I'm also a bit nervous about the brain extraction workflow - we put so many hours on that, and then with the T1w registration it seems things might have changed w.r.t. the code we tested back then. This would be a risky step back.

We also need to generate a reportlet for the T1w-to-T2w co-registration, I'll add it on Monday and also test it locally.

BTW, you'll need ANTs >2.2 to run this.

**Comment by oesteban** [comment]
This is ready for review. I tested only with this gist - https://gist.github.com/oesteban/3c6e71374f99bcabcbd83ead21b4a43b (therefore, N = 1), but I'm positive this will work on other problematic cases.

See the output for this particular subject attached: [report.svg.zip](https://github.com/nipreps/nibabies/files/6099581/report.svg.zip).

**Comment by oesteban** [comment]
Okay @mgxd, I think this is over the finish line. I'm currently testing on a couple of subjects - but I believe this is ready for you to review and test.

I have added one script under `/scripts/` for your convenience - this is what I'm using now to quickly switch between participants.

**Comment by mgxd** [comment]
@oesteban - I polished it up a bit. One problem still remains:

`init_anat_average_wf` produces a `valid_list` output, with the original intention (correct me if I'm wrong) of including the source names to be used later in the derivatives workflow. The workflow is currently blowing up there, here's a crashfile:

<details>
<summary>Crashfile</summary>

```
Node: nibabies_wf.single_subject_01_wf.infant_anat_wf.anat_derivatives_wf.raw_sources
Working directory: /work/nibabies_wf/single_subject_01_wf/infant_anat_wf/anat_derivatives_wf/raw_sources
Node inputs:
bids_root = /data
function_str = def _bids_relative(in_files, bids_root):
    from pathlib import Path
    if not isinstance(in_files, (list, tuple)):
        in_files = [in_files]
    in_files = [str(Path(p).relative_to(bids_root)) for p in in_files]
    return in_files
in_files = <undefined>
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
    result["result"] = node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 516, in run
    result = self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 635, in _run_interface
    return self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 741, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 434, in run
    runtime = self._run_interface(runtime)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/utility/wrappers.py", line 142, in _run_interface
    out = function_handle(**args)
  File "<string>", line 6, in _bids_relative
  File "<string>", line 6, in <listcomp>
  File "/usr/local/miniconda/lib/python3.7/pathlib.py", line 867, in relative_to
    .format(str(self), str(formatted)))
ValueError: '/work/nibabies_wf/single_subject_01_wf/infant_anat_wf/t1w_template_wf/clip_postinu/mapflow/_clip_postinu0/clipped.nii.gz' does not start with '/data'
```

</details>

**Comment by oesteban** [comment]
It should be fixed now - see efae55a.

**Review by mgxd — APPROVED** [review]
Okay, local tests look good. Let's get this in, thanks @oesteban!

**Pull request merged**
