### PR TITLE
ENH: CiftiDilate interface

### PR DESCRIPTION
**Pull request by mgxd**
Preparation for #49 

Currently untested.

### CODE REVIEW

**Comment by mgxd** [comment]
Testing this with a dtseries produced by fMRIPrep. The command mirrors the one in the [DCAN script](https://github.com/DCAN-Labs/dcan-infant-pipeline/blob/247e19e5441cc814cea2f23720caeeb6c6aeadf8/fMRISurface/scripts/SubcorticalAlign_ROIs.sh#L115)

```
wb_command -cifti-dilate sub-01_task-mixedgamblestask_run-1_space-fsLR_den-91k_bold.dtseries.nii COLUMN 0 10 dilated_sub-01_task-mixedgamblestask_run-1_space-fsLR_den-91k_bold.dtseries.nii
```

But I'm running into

```
ERROR: left surface required but not provided
```

**Comment by effigies** [comment]
I wonder if there's a wb_spec dependency that wasn't listed in the script.

**Comment by mgxd** [comment]
After chatting with @ericfeczko it seems their CIFTI is purely volumetric at that step, so no surface information is required.

**Comment by effigies** [comment]
Ah, yeah, it's running on something made at L107.

**Comment by mgxd** [comment]
@effigies I'm going to merge this in so we can then just append new interfaces to `nibabies.interfaces.workbench.py`.

**Pull request merged**
